2020-10-29 01:24:40.935 +03:00 [INF] Starting web host
2020-10-29 01:26:26.405 +03:00 [INF] Starting web host
2020-10-29 01:26:53.721 +03:00 [INF] Starting web host
2020-10-29 01:28:21.985 +03:00 [INF] Starting web host
2020-10-29 01:29:25.051 +03:00 [INF] Starting web host
2020-10-29 01:29:30.126 +03:00 [FTL] Host terminated unexpectedly
System.ArgumentException: Cannot instantiate implementation type 'WebsocketLibrary.WebSocketHandler' for service type 'WebsocketLibrary.WebSocketHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ChatTest.Program.Main(String[] args) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\ChatTest\Program.cs:line 24
2020-10-29 01:31:25.452 +03:00 [INF] Starting web host
2020-10-29 01:33:08.030 +03:00 [INF] Starting web host
2020-10-29 01:37:15.980 +03:00 [INF] Starting web host
2020-10-29 01:45:24.027 +03:00 [INF] Starting web host
2020-10-29 01:47:37.239 +03:00 [INF] Starting web host
2020-10-29 01:47:42.364 +03:00 [FTL] Host terminated unexpectedly
System.ArgumentException: Cannot instantiate implementation type 'WebsocketLibrary.WebSocketHandler' for service type 'WebsocketLibrary.WebSocketHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ChatTest.Program.Main(String[] args) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\ChatTest\Program.cs:line 24
2020-10-29 01:48:42.840 +03:00 [INF] Starting web host
2020-10-29 01:50:42.081 +03:00 [INF] Starting web host
2020-10-29 12:45:20.965 +03:00 [INF] Starting web host
2020-10-29 12:47:13.222 +03:00 [INF] Starting web host
2020-10-29 12:59:30.121 +03:00 [INF] Starting web host
2020-10-29 13:00:05.808 +03:00 [INF] Starting web host
2020-10-29 13:00:22.356 +03:00 [INF] Starting web host
2020-10-29 13:02:42.052 +03:00 [INF] Starting web host
2020-10-29 13:03:36.612 +03:00 [FTL] Host terminated unexpectedly
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: ChatTest.DataBusiness.Handlers.ChatMessageHandler Lifetime: Singleton ImplementationType: ChatTest.DataBusiness.Handlers.ChatMessageHandler': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'ChatTest.DataBusiness.Handlers.ChatMessageHandler'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: ChatTest.DataBusiness.Handlers.ChatMessageHandler Lifetime: Singleton ImplementationType: ChatTest.DataBusiness.Handlers.ChatMessageHandler': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'ChatTest.DataBusiness.Handlers.ChatMessageHandler'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'ChatTest.DataBusiness.Handlers.ChatMessageHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ChatTest.Program.Main(String[] args) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\ChatTest\Program.cs:line 24
2020-10-29 13:03:55.552 +03:00 [INF] Starting web host
2020-10-29 13:05:28.893 +03:00 [INF] Starting web host
2020-10-29 13:09:39.263 +03:00 [INF] Starting web host
2020-10-29 13:22:04.720 +03:00 [INF] Starting web host
2020-10-29 13:23:58.031 +03:00 [INF] Starting web host
2020-10-29 14:33:48.460 +03:00 [INF] Starting web host
2020-10-29 14:35:00.478 +03:00 [INF] Starting web host
2020-10-29 14:35:13.230 +03:00 [INF] Starting web host
2020-10-29 14:36:02.903 +03:00 [INF] Starting web host
2020-10-29 14:36:52.636 +03:00 [INF] Starting web host
2020-10-29 14:37:52.829 +03:00 [INF] Starting web host
2020-10-29 14:38:08.814 +03:00 [INF] Starting web host
2020-10-29 14:39:18.530 +03:00 [INF] Starting web host
2020-10-29 14:50:55.178 +03:00 [INF] Starting web host
2020-10-29 14:52:01.964 +03:00 [INF] Starting web host
2020-10-29 14:59:28.405 +03:00 [INF] Starting web host
2020-10-29 15:08:34.321 +03:00 [INF] Starting web host
2020-10-29 15:08:35.274 +03:00 [INF] New connection
2020-10-29 16:16:51.646 +03:00 [INF] Starting web host
2020-10-29 16:22:48.447 +03:00 [INF] Starting web host
2020-10-29 16:23:04.951 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'ChatTest.DataBusiness.Services.AccountService' while attempting to activate 'ChatTest.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-29 16:25:15.484 +03:00 [INF] Starting web host
2020-10-29 16:28:03.725 +03:00 [INF] Starting web host
2020-10-29 16:34:57.720 +03:00 [INF] Starting web host
2020-10-29 16:41:45.480 +03:00 [INF] Starting web host
2020-10-29 16:50:43.337 +03:00 [INF] Starting web host
2020-10-29 16:53:06.534 +03:00 [INF] Starting web host
2020-10-29 16:53:51.280 +03:00 [INF] Starting web host
2020-10-29 16:55:47.143 +03:00 [INF] Starting web host
2020-10-29 16:59:38.766 +03:00 [INF] Starting web host
2020-10-29 17:11:49.203 +03:00 [INF] Starting web host
2020-10-29 17:13:22.777 +03:00 [INF] Starting web host
2020-10-29 17:13:59.294 +03:00 [INF] Starting web host
2020-10-29 17:16:45.264 +03:00 [INF] Starting web host
2020-10-29 17:19:12.866 +03:00 [INF] Starting web host
2020-10-29 17:24:30.293 +03:00 [INF] Starting web host
2020-10-29 17:26:43.377 +03:00 [INF] Starting web host
2020-10-29 17:29:02.660 +03:00 [INF] Starting web host
2020-10-29 17:30:12.305 +03:00 [WRN] User 4e87ed54-2fe8-4626-a1a6-2a25f5871b6f password validation failed: PasswordRequiresNonAlphanumeric;PasswordRequiresUpper.
2020-10-29 17:31:09.811 +03:00 [INF] Starting web host
2020-10-29 17:31:19.224 +03:00 [WRN] User 1eb100f2-62ac-4ce6-9100-c85cc20e227c password validation failed: PasswordRequiresNonAlphanumeric.
2020-10-29 17:32:35.729 +03:00 [INF] Starting web host
2020-10-29 17:41:34.793 +03:00 [INF] Starting web host
2020-10-29 17:45:27.949 +03:00 [WRN] User 70ffee9f-e27d-49e7-906c-22ca6a6c6f14 validation failed: DuplicateUserName.
2020-10-29 17:45:36.583 +03:00 [WRN] Invalid password for user 93def211-3f17-4e2e-8839-e49aa6270621.
2020-10-29 17:45:36.585 +03:00 [WRN] User 93def211-3f17-4e2e-8839-e49aa6270621 failed to provide the correct password.
2020-10-29 19:03:16.784 +03:00 [INF] Starting web host
2020-10-29 19:05:58.299 +03:00 [INF] Starting web host
2020-10-29 19:06:15.207 +03:00 [INF] New connection
2020-10-29 19:16:07.296 +03:00 [INF] Starting web host
2020-10-29 19:16:11.536 +03:00 [INF] New connection
2020-10-29 19:16:21.015 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Удаленный хост принудительно разорвал существующее подключение.
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-29 19:16:21.192 +03:00 [WRN] The response has already started, the error page middleware will not be executed.
2020-10-29 19:16:21.198 +03:00 [ERR] Connection id "0HM3S4NPOQV4E", Request id "0HM3S4NPOQV4E:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Удаленный хост принудительно разорвал существующее подключение.
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-29 19:16:32.174 +03:00 [INF] Starting web host
2020-10-29 19:16:34.670 +03:00 [INF] New connection
2020-10-29 19:20:00.906 +03:00 [INF] Starting web host
2020-10-29 19:20:02.828 +03:00 [FTL] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
 ---> System.Net.Sockets.SocketException (10048): Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-10-29 19:26:51.741 +03:00 [INF] Starting web host
2020-10-29 19:27:03.754 +03:00 [INF] New connection
2020-10-29 19:27:51.546 +03:00 [INF] Starting web host
2020-10-29 19:28:18.070 +03:00 [INF] Starting web host
2020-10-29 19:28:23.519 +03:00 [INF] New connection
2020-10-29 19:28:58.232 +03:00 [INF] Starting web host
2020-10-29 19:29:01.228 +03:00 [INF] New connection
2020-10-29 19:29:32.203 +03:00 [INF] Starting web host
2020-10-29 19:29:47.488 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute.CreateInstance(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.CreateUncachedFiltersCore(IFilterProvider[] filterProviders, ActionContext actionContext, List`1 filterItems)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.GetAllFilters(IFilterProvider[] filterProviders, ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-29 19:30:16.775 +03:00 [INF] Starting web host
2020-10-29 19:31:15.551 +03:00 [INF] New connection
2020-10-29 22:42:39.312 +03:00 [INF] Starting web host
2020-10-29 22:43:23.834 +03:00 [INF] New connection
2020-10-29 22:44:30.085 +03:00 [INF] Starting web host
2020-10-29 22:44:54.902 +03:00 [INF] Starting web host
2020-10-29 22:48:32.784 +03:00 [INF] New connection
2020-10-29 22:54:27.996 +03:00 [INF] Starting web host
2020-10-29 22:55:13.816 +03:00 [INF] Starting web host
2020-10-29 22:55:16.258 +03:00 [INF] New connection
2020-10-29 22:56:01.718 +03:00 [INF] Starting web host
2020-10-29 22:56:12.165 +03:00 [INF] Starting web host
2020-10-29 22:56:15.771 +03:00 [INF] New connection
2020-10-29 22:56:35.025 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.OperationCanceledException: The read was canceled
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-29 22:56:35.107 +03:00 [WRN] The response has already started, the error page middleware will not be executed.
2020-10-29 22:56:35.113 +03:00 [ERR] Connection id "0HM3S8IOU99J0", Request id "0HM3S8IOU99J0:00000001": An unhandled exception was thrown by the application.
System.OperationCanceledException: The read was canceled
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-29 22:56:53.284 +03:00 [INF] Starting web host
2020-10-29 22:56:56.175 +03:00 [INF] New connection
2020-10-29 22:57:40.401 +03:00 [INF] Starting web host
2020-10-29 22:58:18.506 +03:00 [INF] New connection
2020-10-29 22:59:15.944 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Удаленный хост принудительно разорвал существующее подключение.
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-29 22:59:15.998 +03:00 [WRN] The response has already started, the error page middleware will not be executed.
2020-10-29 22:59:16.003 +03:00 [ERR] Connection id "0HM3S8JTGMJK3", Request id "0HM3S8JTGMJK3:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Удаленный хост принудительно разорвал существующее подключение.
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-29 23:00:11.412 +03:00 [INF] Starting web host
2020-10-29 23:00:15.222 +03:00 [INF] New connection
2020-10-29 23:17:27.322 +03:00 [INF] Starting web host
2020-10-29 23:17:31.771 +03:00 [INF] New connection
2020-10-29 23:19:50.263 +03:00 [INF] Starting web host
2020-10-29 23:20:17.292 +03:00 [INF] Starting web host
2020-10-29 23:20:19.734 +03:00 [INF] New connection
2020-10-29 23:36:33.997 +03:00 [INF] Starting web host
2020-10-29 23:36:37.919 +03:00 [INF] New connection
2020-10-29 23:37:38.167 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Удаленный хост принудительно разорвал существующее подключение.
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-29 23:37:38.203 +03:00 [WRN] The response has already started, the error page middleware will not be executed.
2020-10-29 23:37:38.208 +03:00 [ERR] Connection id "0HM3S99APL5C2", Request id "0HM3S99APL5C2:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Удаленный хост принудительно разорвал существующее подключение.
 ---> System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at WebsocketLibrary.WebSocketManagerMiddleware.Receive(WebSocket socket, Action`2 handleMessage) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 52
   at WebsocketLibrary.WebSocketManagerMiddleware.Invoke(HttpContext context) in C:\Users\marat\Desktop\Job\Test\ChatTest\ChatTest\WebsocketLibrary\WebSocketManagerMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-10-29 23:38:11.795 +03:00 [INF] Starting web host
2020-10-29 23:38:13.793 +03:00 [FTL] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
 ---> System.Net.Sockets.SocketException (10048): Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-10-29 23:38:40.344 +03:00 [INF] Starting web host
2020-10-29 23:41:11.144 +03:00 [INF] Starting web host
2020-10-29 23:41:23.052 +03:00 [INF] New connection
2020-10-29 23:42:26.342 +03:00 [INF] New message
2020-10-29 23:45:36.420 +03:00 [INF] Starting web host
2020-10-29 23:45:38.752 +03:00 [INF] New connection
2020-10-30 00:40:14.942 +03:00 [INF] Starting web host
2020-10-30 00:40:21.161 +03:00 [INF] New connection
2020-10-30 00:41:22.659 +03:00 [INF] Starting web host
2020-10-30 00:41:29.111 +03:00 [INF] New connection
2020-10-30 00:42:15.888 +03:00 [INF] New message
2020-10-30 00:42:25.782 +03:00 [INF] New message
2020-10-30 00:42:55.764 +03:00 [INF] New message
2020-10-30 00:46:35.531 +03:00 [INF] Starting web host
2020-10-30 00:46:38.595 +03:00 [INF] New connection
2020-10-30 00:46:44.369 +03:00 [INF] New message
2020-10-30 00:46:48.038 +03:00 [INF] New message
2020-10-30 00:46:51.225 +03:00 [INF] New message
2020-10-30 00:46:53.846 +03:00 [INF] New message
